[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "api"

[dev]
  framework = "#custom"
  command = "npm run dev --workspace=frontend"
  targetPort = 5173
  port = 8888
  publish = "frontend/dist"
  functions = "api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 