name = "ai-flashcard-worker"
main = "backend/worker.js"
compatibility_date = "2024-01-30"

[vars]
# Add your environment variables here
# PERPLEXITY_API_KEY = "your-api-key"  # Don't put the actual key here

# Use secrets for sensitive values
# Run: wrangler secret put PERPLEXITY_API_KEY
# to set the API key securely 